language: android
dist: trusty
sudo: false
#jdk: oraclejdk8

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-30.0.1

    # The SDK version used to compile your project
    - android-30

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

- before_install:
  - yes | sdkmanager "platforms;android-30"

script:
  - ./gradlew assembleDebug
